site_name: Sistema de Gestão de Presença
repo_url: 
theme:
  name: material
  custom_dir: overrides
  logo: img\logo_acessa.png
  favicon: img\logo_acessa1.png
  features:
    - navigation.tabs
    - navigation.top
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "orange"
      accent: "purple"
      toggle:
        icon: material/brightness-4
        name: Alternar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "grey"
      accent: "orange"
      toggle:
        icon: material/brightness-7
        name: Alternar para modo claro
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Sobre: 
    - Sobre: Sobre/Sobre.md
    - Visão do Produto: Sobre/Visao_do_produto.md
    - Benchmarking: Sobre/Benchmarking.md

  - Planejamento:
      - Metodologia: Planejamento/Metodologia.md
      - Ferramentas: Planejamento/Ferramentas.md
      - Cronograma: Planejamento/Cronograma.md
      - Matriz CSD: Planejamento/Matriz_CSD.md
     

  - Pré-Rastreabilidade:
      - Rich Picture: Pré-Rastriabilidade/Rich-picture.md
  

  - Elicitação:
      - Perfil de usuário: Elicitação/Perfil_usuario.md
      - Requisitos Elicitados: Elicitação/Requisitos-Elicitados.md
      - Priorização:
          - Matriz Esforço x Impacto: Elicitação/Priorização/matrizesforco_impacto.md
          - First Things First: Elicitação/Priorização/First_Things_First.md
  - Arquitetura: 
    - DER: rquitetura/DER.md

  - Modelagem:
      - Casos de Uso: Modelagem/Casos-de-uso.md
      - Ágil:
          - Histórias de usuário: Modelagem/Ágil/HistoriaUsuario.md
          - Backlog: Modelagem/Ágil/Backlog.md

  - Análise:
      - Prototipação: Análise/Prototipacao.md


 
 
